#ifndef COLOR_TERM_MACRO_H_
# define COLOR_TERM_MACRO_H_

#define ESC   "\x1B"
#define RST   "\x1B[0m"
#define BLACK   "\x1B[30m"
#define RED     "\x1B[31m"
#define GREEN   "\x1B[32m"
#define YELLOW  "\x1B[33m"
#define BLUE    "\x1B[34m"
#define MAGENTA "\x1B[35m"
#define CYAN    "\x1B[36m"
#define WHITE   "\x1B[37m"
#define BKGBLACK   "\x1B[40m"
#define BKGRED     "\x1B[41m"
#define BKGGREEN   "\x1B[42m"
#define BKGYELLOW  "\x1B[43m"
#define BKGBLUE    "\x1B[44m"
#define BKGMAGENTA "\x1B[45m"
#define BKGCYAN    "\x1B[46m"
#define BKGWHITE   "\x1B[47m"
#define BRTBLACK   "\x1B[90m"
#define BRTRED     "\x1B[91m"
#define BRTGREEN   "\x1B[92m"
#define BRTYELLOW  "\x1B[93m"
#define BRTBLUE    "\x1B[94m"
#define BRTMAGENTA "\x1B[95m"
#define BRTCYAN    "\x1B[96m"
#define BRTWHITE   "\x1B[97m"
#define BRTBKGBLACK   "\x1B[100m"
#define BRTBKGRED     "\x1B[101m"
#define BRTBKGGREEN   "\x1B[102m"
#define BRTBKGYELLOW  "\x1B[103m"
#define BRTBKGBLUE    "\x1B[104m"
#define BRTBKGMAGENTA "\x1B[105m"
#define BRTBKGCYAN    "\x1B[106m"
#define BRTBKGWHITE   "\x1B[107m"
#define BOLD        "\x1B[1m"
#define LIGHT       "\x1B[2m"
#define ITALIC      "\x1B[3m" //Not widely supported
#define UNDERLINE   "\x1B[4m"
#define BLINK       "\x1B[5m"
#define STOPBLINK   "\x1B[25m"

#endif